[package]
authors = ["Benn Sundsrud <benn.sundsrud@gmail.com>"]
license = "MIT/Apache-2.0"
name    = "ruuls"
version = "0.1.0"

[features]
default = []

[dependencies]
serde = { version = "1.0.117", features = ["derive"], optional = true }
